
name: Add PowerShell module to Azure Automation
on:
  workflow_dispatch:
jobs:
  addmodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
          enable-AzPSSession: true

      - name: Add the module
        uses: ./
        id: add
        with:
          resource-group-name: azautomation
          automation-account-name: import-tester