name: Add PowerShell module to Azure Automation
on:
  push:
jobs:
  addmodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDENTIAL }}
          enable-AzPSSession: true

      - name: Add the repo module
        uses: ./
        id: add
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_PAT }}
        with:
          resource-group-name: azautomation
          automation-account-name: import-tester
          module-name: archive

      - name: Add the dbatools module
        if: always()
        uses: ./
        id: dbatools
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_PAT }}
        with:
          resource-group-name: azautomation
          automation-account-name: import-tester
          module-uri: https://github.com/dataplat/dbatools/archive/refs/heads/development.zip
          module-name: dbatools

      - name: Add the repo module by relative file name
        if: always()
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_PAT }}
        with:
          resource-group-name: azautomation
          automation-account-name: import-tester
          module-name: archive
          module-path: ./tests/sample/archive.psm1

      - name: Add the repo module by absolute file name
        if: always()
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_PAT }}
        with:
          resource-group-name: azautomation
          automation-account-name: import-tester
          module-name: archive
          module-path: /home/runner/work/azautomodule/azautomodule/tests/sample