name: Add PowerShell module to Azure Automation
on:
  push:
jobs:
  addmodule:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZ_CREDENTIAL }}
          enable-AzPSSession: true

      - name: Add the module
        uses: ./
        id: add
        env:
          GITHUB_TOKEN: ${{ secrets.GIST_PAT }}
        with:
          resource-group-name: azautomation
          automation-account-name: import-tester