
name: Add PowerShell module to Azure Automation
on:
  workflow_dispatch:
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - uses: potatoqualitee/azautomodule@main
        id: add
        with:
          resource-group-name: tech.lgbt
          automation-account-name: something
        env:
          ACCESS_TOKEN: "${{ secrets.ACCESS_TOKEN }}"